### ISSUE TITLE
Tracking: inviting people to the team

### ISSUE THREAD

**Issue by booyaa** [rust-community/content-team#8]
- [x] TWiR Team /via https://github.com/cmr/this-week-in-rust/issues/607
- [x] Michael Gattozzi (chronicle.rs) @mgattozzi
- [ ] Matthias Endler ([hello-rust show]( https://hello-rust.show/) @mre
- [ ] Chris Krycho (New Rustacean) @chriskrycho
---

Please suggest anyone else we should invite that produces Rust related content or has an interest in this area by commenting on this thread.

**Comment by booyaa** [comment]
Opened because of #6

**Comment by bstrie** [comment]
How about Chris Krycho, of the New Rustacean podcast?

**Comment by mgattozzi** [comment]
I've started work on [chronicle.rs](https://chronicle.rs) which seeks to delve more into Rust's history as a resource for people to look at as well as answer interesting questions such as "Why do we call libraries crates?"

**Comment by o0Ignition0o** [comment]
May I suggest Matthias Endler ( @mre ),  who runs the https://hello-rust.show/ ? (pun intended)
